server:
   port: 8083
spring:
   zipkin:
      base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
      discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
   sleuth:
      sampler:
        probability: 1.0  #采样的百分比
   application:
       name: service-order
   datasource:
        url: jdbc:mysql://localhost:3306/fan?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
        hibernate:
           ddl-auto: update
        show-sql: true
   cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
        sentinel:  # 链入到sentinel控制台
            transport:
                 port: 9999 # 跟控制台交流的端口， 随意指定一个端口即可。
                 dashboard: localhost:8080 # 指定控制台服务的地址
# 开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true